export const KRYPTOS_ALPHABET = "KRYPTOSABCDEFGHIJLMNQUVWXZ";
export const NORMAL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const K1_CIPHERTEXT = "EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJYQTQUXQBQVYUVLLTREVJYQTMKYRDMFD";
export const K2_CIPHERTEXT = "VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?DQMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEUNAQZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJHKFWHKUWQLSZFTIHHDDDUVH?DWKBFUFPWNTDFIYCUQZEREEVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEEXBDMVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUMEBEDMHDAFMJGZNUPLGEWJLLAETG";
export const K3_CIPHERTEXT = "ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNREYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLPIIACAEWMTWNDITEENRAHCTENEUDRETNHAEOETFOLSEDTIWENHAEIOYTEYQHEENCTAYCREIFTBRSPAMHHEWENATAMATEGYEERLBTEEFOASFIOTUETUAEOTOARMAEERTNRTIBSEDDNIAAHTTMSTEWPIEROAGRIEWFEBAECTDDHILCEIHSITEGOEAOSDDRYDLORITRKLMLEHAGTDHARDPNEOHMGFMFEUHEECDMRIPFEIMEHNLSSTTRTVDOHW";
export const K4_CIPHERTEXT = "OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR";
export const K1_PLAINTEXT = "BETWEENSUBTLESHADINGANDTHEABSENCEOFLIGHTLIESTHENUANCEOFIQLUSION";
export const K2_PLAINTEXT = "ITWASTOTALLYINVISIBLEHOWSTHATPOSSIBLE?THEYUSEDTHEEARTHSMAGNETICFIELDXTHEINFORMATIONWASGATHEREDANDTRANSMITTEDUNDERGRUUNDTOANUNKNOWNLOCATIONXDOESLANGLEYKNOWABOUTTHIS?THEYSHOULDITSBURIEDOUTTHERESOMEWHEREXWHOKNOWSTHEEXACTLOCATION?ONLYWWTHISWASHISLASTMESSAGEXTHIRTYEIGHTDEGREESFIFTYSEVENMINUTESSIXPOINTFIVESECONDSNORTHSEVENTYSEVENDEGREESEIGHTMINUTESFORTYFOURSECONDSWESTIDBYROWS";
export const K3_PLAINTEXT = "SLOWLYDESPARATLYSLOWLYTHEREMAINSOFPASSAGEDEBRISTHATENCUMBEREDTHELOWERPARTOFTHEDOORWAYWASREMOVEDWITHTREMBLINGHANDSIMADEATINYBREACHINTHEUPPERLEFTHANDCORNERANDTHENWIDENINGTHEHOLEALITTLEIINSERTEDTHECANDLEANDPEEREDINTHEHOTAIR" +
  "ESCAPINGFROMTHECHAMBERCAUSEDTHEFLAMETOFLICKERBUTPRESENTLYDETAILSOFTHEROOMWITHINEMERGEDFROMTHEMISTXCANYOUSEEANYTHINGQ";
export const K4_CRIBS = "EASTNORTHEASTBERLINCLOCK";

export const KRYPTOS_LEFT_PLATE_COLUMNS = 33;
export const KRYPTOS_LEFT_PLATE = [
  "EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJ",
  "YQTQUXQBQVYUVLLTREVJYQTMKYRDMFD",
  "VFPJUDEEHZWETZYVGWHKKQETGFQJNCE",
  "GGWHKK?DQMCPFQZDQMMIAGPFXHQRLG",
  "TIMVMZJANQLVKQEDAGDVFRPJUNGEUNA",
  "QZGZLECGYUXUEENJTBJLBQCRTBJDFHRR",
  "YIZETKZEMVDUFKSJHKFWHKUWQLSZFTI",
  "HHDDDUVH?DWKBFUFPWNTDFIYCUQZERE",
  "EVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDX",
  "FLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKF",
  "FHQNTGPUAECNUVPDJMQCLQUMUNEDFQ",
  "ELZZVRRGKFFVOEEXBDMVPNFQXEZLGRE",
  "DNQFMPNZGLFLPMRJQYALMGNUVPDXVKP",
  "DQUMEBEDMHDAFMJGZNUPLGEWJLLAETG",
  "ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIA",
  "CHTNREYULDSLLSLLNOHSNOSMRWXMNE",
  "TPRNGATIHNRARPESLNNELEBLPIIACAE",
  "WMTWNDITEENRAHCTENEUDRETNHAEOE",
  "TFOLSEDTIWENHAEIOYTEYQHEENCTAYCR",
  "EIFTBRSPAMHHEWENATAMATEGYEERLB",
  "TEEFOASFIOTUETUAEOTOARMAEERTNRTI",
  "BSEDDNIAAHTTMSTEWPIEROAGRIEWFEB",
  "AECTDDHILCEIHSITEGOEAOSDDRYDLORIT",
  "RKLMLEHAGTDHARDPNEOHMGFMFEUHE",
  "ECDMRIPFEIMEHNLSSTTRTVDOHW?OBKR",
  "UOXOGHULBSOLIFBBWFLRVQQPRNGKSSO",
  "TWTQSJQSSEKZZWATJKLUDIAWINFBNYP",
  "VTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR",
].map(row => row.padEnd(KRYPTOS_LEFT_PLATE_COLUMNS, " ")).join("");

export const KRYPTOS_RIGHT_PLATE_COLUMNS = 32;
export const KRYPTOS_RIGHT_PLATE = [
  " ABCDEFGHIJKLMNOPQRSTUVWXYZABCD",
  "AKRYPTOSABCDEFGHIJLMNQUVWXZKRYP",
  "BRYPTOSABCDEFGHIJLMNQUVWXZKRYPT",
  "CYPTOSABCDEFGHIJLMNQUVWXZKRYPTO",
  "DPTOSABCDEFGHIJLMNQUVWXZKRYPTOS",
  "ETOSABCDEFGHIJLMNQUVWXZKRYPTOSA",
  "FOSABCDEFGHIJLMNQUVWXZKRYPTOSAB",
  "GSABCDEFGHIJLMNQUVWXZKRYPTOSABC",
  "HABCDEFGHIJLMNQUVWXZKRYPTOSABCD",
  "IBCDEFGHIJLMNQUVWXZKRYPTOSABCDE",
  "JCDEFGHIJLMNQUVWXZKRYPTOSABCDEF",
  "KDEFGHIJLMNQUVWXZKRYPTOSABCDEFG",
  "LEFGHIJLMNQUVWXZKRYPTOSABCDEFGH",
  "MFGHIJLMNQUVWXZKRYPTOSABCDEFGHI",
  "NGHIJLMNQUVWXZKRYPTOSABCDEFGHIJL",
  "OHIJLMNQUVWXZKRYPTOSABCDEFGHIJL",
  "PIJLMNQUVWXZKRYPTOSABCDEFGHIJLM",
  "QJLMNQUVWXZKRYPTOSABCDEFGHIJLMN",
  "RLMNQUVWXZKRYPTOSABCDEFGHIJLMNQ",
  "SMNQUVWXZKRYPTOSABCDEFGHIJLMNQU",
  "TNQUVWXZKRYPTOSABCDEFGHIJLMNQUV",
  "UQUVWXZKRYPTOSABCDEFGHIJLMNQUVW",
  "VUVWXZKRYPTOSABCDEFGHIJLMNQUVWX",
  "WVWXZKRYPTOSABCDEFGHIJLMNQUVWXZ",
  "XWXZKRYPTOSABCDEFGHIJLMNQUVWXZK",
  "YXZKRYPTOSABCDEFGHIJLMNQUVWXZKR",
  "ZZKRYPTOSABCDEFGHIJLMNQUVWXZKRY",
  " ABCDEFGHIJKLMNOPQRSTUVWXYZABCD",
].map(row => row.padEnd(KRYPTOS_RIGHT_PLATE_COLUMNS, " ")).join("");

export const ENGLISH_BOOK_SAMPLES = [
  { title: "Pride and Prejudice", text: "ITISATRUTHUNIVERSALLYACKNOWLEDGEDTHATASINGLEMANINPOSSESSIONOFAGOODFORTUNEMUSTBEINWANTOFAWIFE" },
  { title: "Moby-Dick", text: "CALLMEISHMAELSOMEYEARSAGONEVERMINDHOWLONGPRECISELYHAVINGLITTLEORNOMONEYINMYPURSEANDNOTHINGPARTICULARTOINTERESTMEONSHORE" },
  { title: "Alice's Adventures in Wonderland", text: "ALICEWASBEGINNINGTOGETVERYTIREDOFSITTINGBYHERSISTERONTHEBANKANDOFHAVINGNOTHINGTODOONCEORTWICESHEHADPEEPEDINTOTHEBOOK" },
  { title: "A Tale of Two Cities", text: "ITWASTHEBESTOFTIMESITWASTHEWORSTOFTIMESITWASTHEAGEOFWISDOMITWASTHEAGEOFFOOLISHNESSITWASTHEEPOCHOFBELIEF" },
  { title: "Frankenstein", text: "IAMBYBIRTHAGENEVESEANDMYFAMILYISONEOFTHEMOSTDISTINGUISHEDOFTHATREPUBLICMYANCESTORSHADBEENFORMANYYEARSCOUNSELLORSANDSYNDICS" },
  { title: "The Time Machine", text: "THETIMETRAVELLERFORSOITWILLBECONVENIENTTOSPEAKOFHIMWASEXPOUNDINGARECONDITEMATTERTOUS" },
  { title: "The Wonderful Wizard of Oz", text: "DOROTHYLIVEDINTHEMIDSTOFTHEGREATKANSASPRARIESWITHUNCLEHENRYWHOWASFARMERANDAUNTEMWHOWASTHEFARMERSWIFE" },
  { title: "Treasure Island", text: "SQUIRETRELAWNEYDRLIVESEYANDTHERESTOFTHESEGENTLEMENHAVINGASKEDMETOWRITEDOWNTHEWHOLEPARTICULARSABOUTTREASUREISLAND" },
];

export function randomEnglishBookSample() {
  return ENGLISH_BOOK_SAMPLES[Math.floor(Math.random() * ENGLISH_BOOK_SAMPLES.length)];
}

export const GRID_OPERATIONS = {
  add: { symbol: "⊕", label: "add A + B", calculate: (a, b, length) => (a + b) % length },
  subtract: { symbol: "−", label: "subtract A − B", calculate: (a, b, length) => (a - b + length) % length },
  reverseSubtract: { symbol: "−", label: "subtract B − A", reverseOperands: true, calculate: (a, b, length) => (b - a + length) % length },
};

export function cleanText(value) {
  return (value || "").toUpperCase().replace(/[^A-Z?]/g, "");
}

export function cleanUnique(value) {
  return [...new Set((value || "").toUpperCase().replace(/\s/g, ""))].join("");
}

export function positionalK4Cribs() {
  const slots = Array(97).fill("?");
  const place = (oneBasedPosition, text) => [...text].forEach((letter, offset) => { slots[oneBasedPosition - 1 + offset] = letter; });
  place(22, "EASTNORTHEAST");
  place(64, "BERLINCLOCK");
  return slots.join("");
}

export function combineCipherLetters(a, b, operation, alphabet) {
  if (!a || !b || a === " " || b === " ") return " ";
  const left = alphabet.indexOf(a);
  const right = alphabet.indexOf(b);
  if (left < 0 || right < 0 || alphabet.length < 2) return "?";
  const definition = GRID_OPERATIONS[operation] || GRID_OPERATIONS.add;
  return alphabet[definition.calculate(left, right, alphabet.length)];
}

export function combineCipherText(base, overlay, operation, alphabet) {
  const length = Math.min(base.text.length, overlay.text.length);
  let text = "";
  for (let index = 0; index < length; index++) text += combineCipherLetters(base.text[index], overlay.text[index], operation, alphabet);
  return text;
}

export function combineAlignedCipherText(operandA, operandB, operation, alphabet, alignment) {
  const topIsA = alignment.topOperand === "a";
  const top = topIsA ? operandA : operandB;
  const base = topIsA ? operandB : operandA;
  const rowOffset = Number.isFinite(alignment.rowOffset) ? Math.round(alignment.rowOffset) : 0;
  const columnOffset = Number.isFinite(alignment.columnOffset) ? Math.round(alignment.columnOffset) : 0;
  const baseRows = Math.ceil(base.text.length / base.cols);
  let text = "";
  let compactText = "";
  let alignedCount = 0;
  const matches = [];
  for (let topIndex = 0; topIndex < top.text.length; topIndex++) {
    const baseRow = Math.floor(topIndex / top.cols) + rowOffset;
    const baseColumn = topIndex % top.cols + columnOffset;
    const baseIndex = baseRow * base.cols + baseColumn;
    if (baseRow < 0 || baseRow >= baseRows || baseColumn < 0 || baseColumn >= base.cols || baseIndex < 0 || baseIndex >= base.text.length) {
      text += " ";
      continue;
    }
    alignedCount++;
    const a = topIsA ? top.text[topIndex] : base.text[baseIndex];
    const b = topIsA ? base.text[baseIndex] : top.text[topIndex];
    const combined = combineCipherLetters(a, b, operation, alphabet);
    text += combined;
    if (combined !== " ") compactText += combined;
    matches.push({ topIndex, baseIndex, a, b, result: combined });
  }
  const firstAlignedColumn = Math.max(0, -columnOffset);
  const lastAlignedColumn = Math.min(top.cols, base.cols - columnOffset);
  const overlapColumns = Math.max(1, lastAlignedColumn - firstAlignedColumn);
  return { text, compactText, columns: top.cols, overlapColumns, alignedCount, combinedCount: compactText.length, matches };
}
