export const KRYPTOS_ALPHABET = "KRYPTOSABCDEFGHIJLMNQUVWXZ";
export const NORMAL_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const K1_CIPHERTEXT = "EMUFPHZLRFAXYUSDJKZLDKRNSHGNFIVJYQTQUXQBQVYUVLLTREVJYQTMKYRDMFD";
export const K2_CIPHERTEXT = "VFPJUDEEHZWETZYVGWHKKQETGFQJNCEGGWHKK?DQMCPFQZDQMMIAGPFXHQRLGTIMVMZJANQLVKQEDAGDVFRPJUNGEUNAQZGZLECGYUXUEENJTBJLBQCRTBJDFHRRYIZETKZEMVDUFKSJHKFWHKUWQLSZFTIHHDDDUVH?DWKBFUFPWNTDFIYCUQZEREEVLDKFEZMOQQJLTTUGSYQPFEUNLAVIDXFLGGTEZ?FKZBSFDQVGOGIPUFXHHDRKFFHQNTGPUAECNUVPDJMQCLQUMUNEDFQELZZVRRGKFFVOEEXBDMVPNFQXEZLGREDNQFMPNZGLFLPMRJQYALMGNUVPDXVKPDQUMEBEDMHDAFMJGZNUPLGEWJLLAETG";
export const K3_CIPHERTEXT = "ENDYAHROHNLSRHEOCPTEOIBIDYSHNAIACHTNREYULDSLLSLLNOHSNOSMRWXMNETPRNGATIHNRARPESLNNELEBLPIIACAEWMTWNDITEENRAHCTENEUDRETNHAEOETFOLSEDTIWENHAEIOYTEYQHEENCTAYCREIFTBRSPAMHHEWENATAMATEGYEERLBTEEFOASFIOTUETUAEOTOARMAEERTNRTIBSEDDNIAAHTTMSTEWPIEROAGRIEWFEBAECTDDHILCEIHSITEGOEAOSDDRYDLORITRKLMLEHAGTDHARDPNEOHMGFMFEUHEECDMRIPFEIMEHNLSSTTRTVDOHW";
export const K4_CIPHERTEXT = "OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR";
export const K1_PLAINTEXT = "BETWEENSUBTLESHADINGANDTHEABSENCEOFLIGHTLIESTHENUANCEOFIQLUSION";
export const K2_PLAINTEXT = "ITWASTOTALLYINVISIBLEHOWSTHATPOSSIBLE?THEYUSEDTHEEARTHSMAGNETICFIELDXTHEINFORMATIONWASGATHEREDANDTRANSMITTEDUNDERGRUUNDTOANUNKNOWNLOCATIONXDOESLANGLEYKNOWABOUTTHIS?THEYSHOULDITSBURIEDOUTTHERESOMEWHEREXWHOKNOWSTHEEXACTLOCATION?ONLYWWTHISWASHISLASTMESSAGEXTHIRTYEIGHTDEGREESFIFTYSEVENMINUTESSIXPOINTFIVESECONDSNORTHSEVENTYSEVENDEGREESEIGHTMINUTESFORTYFOURSECONDSWESTIDBYROWS";
export const K3_PLAINTEXT = "SLOWLYDESPARATLYSLOWLYTHEREMAINSOFPASSAGEDEBRISTHATENCUMBEREDTHELOWERPARTOFTHEDOORWAYWASREMOVEDWITHTREMBLINGHANDSIMADEATINYBREACHINTHEUPPERLEFTHANDCORNERANDTHENWIDENINGTHEHOLEALITTLEIINSERTEDTHECANDLEANDPEEREDINTHEHOTAIR" +
  "ESCAPINGFROMTHECHAMBERCAUSEDTHEFLAMETOFLICKERBUTPRESENTLYDETAILSOFTHEROOMWITHINEMERGEDFROMTHEMISTXCANYOUSEEANYTHINGQ";
export const K4_CRIBS = "EASTNORTHEASTBERLINCLOCK";

export const ENGLISH_BOOK_SAMPLES = [
  { title: "Pride and Prejudice", text: "ITISATRUTHUNIVERSALLYACKNOWLEDGEDTHATASINGLEMANINPOSSESSIONOFAGOODFORTUNEMUSTBEINWANTOFAWIFE" },
  { title: "Moby-Dick", text: "CALLMEISHMAELSOMEYEARSAGONEVERMINDHOWLONGPRECISELYHAVINGLITTLEORNOMONEYINMYPURSEANDNOTHINGPARTICULARTOINTERESTMEONSHORE" },
  { title: "Alice's Adventures in Wonderland", text: "ALICEWASBEGINNINGTOGETVERYTIREDOFSITTINGBYHERSISTERONTHEBANKANDOFHAVINGNOTHINGTODOONCEORTWICESHEHADPEEPEDINTOTHEBOOK" },
  { title: "A Tale of Two Cities", text: "ITWASTHEBESTOFTIMESITWASTHEWORSTOFTIMESITWASTHEAGEOFWISDOMITWASTHEAGEOFFOOLISHNESSITWASTHEEPOCHOFBELIEF" },
  { title: "Frankenstein", text: "IAMBYBIRTHAGENEVESEANDMYFAMILYISONEOFTHEMOSTDISTINGUISHEDOFTHATREPUBLICMYANCESTORSHADBEENFORMANYYEARSCOUNSELLORSANDSYNDICS" },
  { title: "The Time Machine", text: "THETIMETRAVELLERFORSOITWILLBECONVENIENTTOSPEAKOFHIMWASEXPOUNDINGARECONDITEMATTERTOUS" },
  { title: "The Wonderful Wizard of Oz", text: "DOROTHYLIVEDINTHEMIDSTOFTHEGREATKANSASPRARIESWITHUNCLEHENRYWHOWASFARMERANDAUNTEMWHOWASTHEFARMERSWIFE" },
  { title: "Treasure Island", text: "SQUIRETRELAWNEYDRLIVESEYANDTHERESTOFTHESEGENTLEMENHAVINGASKEDMETOWRITEDOWNTHEWHOLEPARTICULARSABOUTTREASUREISLAND" },
];

export function randomEnglishBookSample() {
  return ENGLISH_BOOK_SAMPLES[Math.floor(Math.random() * ENGLISH_BOOK_SAMPLES.length)];
}

export const GRID_OPERATIONS = {
  add: { symbol: "⊕", label: "add", calculate: (a, b, length) => (a + b) % length },
  subtract: { symbol: "⊖", label: "subtract", calculate: (a, b, length) => (a - b + length) % length },
};

export function cleanText(value) {
  return (value || "").toUpperCase().replace(/[^A-Z?]/g, "");
}

export function cleanUnique(value) {
  return [...new Set((value || "").toUpperCase().replace(/\s/g, ""))].join("");
}

export function positionalK4Cribs() {
  const slots = Array(97).fill("?");
  const place = (oneBasedPosition, text) => [...text].forEach((letter, offset) => { slots[oneBasedPosition - 1 + offset] = letter; });
  place(22, "EASTNORTHEAST");
  place(64, "BERLINCLOCK");
  return slots.join("");
}

export function combineCipherLetters(a, b, operation, alphabet) {
  if (!a || !b || a === " " || b === " ") return " ";
  const left = alphabet.indexOf(a);
  const right = alphabet.indexOf(b);
  if (left < 0 || right < 0 || alphabet.length < 2) return "?";
  const definition = GRID_OPERATIONS[operation] || GRID_OPERATIONS.add;
  return alphabet[definition.calculate(left, right, alphabet.length)];
}

export function combineCipherText(base, overlay, operation, alphabet) {
  const length = Math.min(base.text.length, overlay.text.length);
  let text = "";
  for (let index = 0; index < length; index++) text += combineCipherLetters(base.text[index], overlay.text[index], operation, alphabet);
  return text;
}
